[env]
DEFMT_LOG = "trace"

[tasks.polling]
run = "cargo run --example polling"

[tasks.blocking]
run = "cargo run --example blocking"

[tasks.interrupt]
run = "cargo run --example interrupt"

[tasks.dma]
run = "cargo run --example dma"

[tasks.embassy]
run = "cargo run --example embassy"
